import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | Super Sales',
  description: 'Terms of Service for Super Sales - B2B AI-powered sales intelligence platform',
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-12">
          <div className="inline-flex items-center px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 text-sm font-medium mb-4">
            Legal
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-4">
            Terms of Service
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mb-2">
            B2B SaaS - SuperSales
          </p>
          <div className="flex flex-wrap gap-4 text-sm text-gray-500 dark:text-gray-500">
            <span>Effective date: December 12, 2025</span>
            <span>Last updated: January 7, 2026</span>
          </div>
          <div className="mt-4 flex flex-wrap gap-2">
            <span className="px-2 py-1 bg-gray-100 dark:bg-zinc-800 text-gray-600 dark:text-gray-400 text-xs rounded">Authoritative language: English</span>
            <span className="px-2 py-1 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 text-xs rounded font-medium">B2B only - No consumer use</span>
          </div>
        </div>

        {/* Introduction */}
        <div className="mb-10 p-5 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800">
          <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
            These Terms of Service (&quot;Terms&quot;) govern access to and use of the SuperSales platform and related services (the &quot;Services&quot;). By accessing or using the Services, you agree to be bound by these Terms on behalf of the legal entity you represent (&quot;Customer&quot;, &quot;you&quot;).
          </p>
        </div>

        {/* Content */}
        <div className="prose prose-gray dark:prose-invert max-w-none">

          {/* Section 1 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">1. Legal Entity &amp; Operator</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              The Services are operated by:
            </p>
            <div className="p-4 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 mb-4">
              <p className="text-gray-900 dark:text-white font-semibold">Arcelis FZE</p>
              <p className="text-gray-600 dark:text-gray-400 text-sm">Commercial Registration No.: 4422325.01</p>
              <p className="text-gray-600 dark:text-gray-400 text-sm">Business Centre, Sharjah Publishing City Free Zone</p>
              <p className="text-gray-600 dark:text-gray-400 text-sm">Sharjah, United Arab Emirates</p>
              <p className="text-gray-600 dark:text-gray-400 text-sm mt-2">Contact: support@supersales.dev</p>
            </div>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              &quot;SuperSales&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot; refers to Arcelis FZE.
            </p>
          </section>

          {/* Section 2 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">2. Definitions</h2>
            <ul className="space-y-3 text-gray-600 dark:text-gray-400">
              <li><strong className="text-gray-900 dark:text-white">Account:</strong> the Customer&apos;s registered account on the SuperSales platform.</li>
              <li><strong className="text-gray-900 dark:text-white">Authorized Users:</strong> Customer&apos;s employees, contractors, or agents authorized to access the Services.</li>
              <li><strong className="text-gray-900 dark:text-white">Content:</strong> audio files, transcriptions, text, or data submitted by or on behalf of Customer.</li>
              <li><strong className="text-gray-900 dark:text-white">AI Outputs:</strong> scores, analyses, insights, coaching feedback, summaries, or recommendations generated by the Services.</li>
              <li><strong className="text-gray-900 dark:text-white">Documentation:</strong> any documentation or policies made available by SuperSales.</li>
              <li><strong className="text-gray-900 dark:text-white">Fees:</strong> subscription fees payable for the Services.</li>
              <li><strong className="text-gray-900 dark:text-white">Seat:</strong> a paid access right for one Authorized User.</li>
              <li><strong className="text-gray-900 dark:text-white">Third-Party Services:</strong> external tools used by Customer (e.g., note-takers or recording tools).</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">3. Scope of Services</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              SuperSales provides a B2B AI-powered sales intelligence and coaching platform designed to analyze sales calls and deliver informational insights, scoring, and commercial recommendations.
            </p>

            <h3 className="text-xl font-medium text-gray-900 dark:text-white mb-3 mt-6">Informational Nature</h3>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>AI Outputs are strictly advisory and informational.</li>
              <li>SuperSales does not perform automated decision-making.</li>
              <li>Human review and validation are mandatory before any action is taken.</li>
              <li>SuperSales does not guarantee any commercial outcome, performance improvement, or financial result.</li>
              <li>Nothing in these Terms creates any fiduciary duty, partnership, agency, or advisory relationship between SuperSales and the Customer.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">4. Eligibility - B2B Only</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              The Services are offered exclusively to business entities.
            </p>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              By using the Services, you confirm that you act on behalf of a legal entity and have authority to bind it.
            </p>
          </section>

          {/* Section 5 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">5. Customer Responsibilities</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              The Customer is solely responsible for:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2 mb-4">
              <li>Ensuring the legality of recording sales calls</li>
              <li>Obtaining all required consents and notices</li>
              <li>Complying with applicable privacy, data protection, employment, and telecommunications laws</li>
              <li>Ensuring Content does not infringe third-party rights</li>
            </ul>
            <div className="p-4 bg-amber-50 dark:bg-amber-900/20 rounded-lg border border-amber-200 dark:border-amber-800">
              <p className="text-amber-800 dark:text-amber-300 text-sm">
                <strong>Important:</strong> SuperSales does not verify the legality, consent, or compliance of Customer Content. The Customer is responsible for all activity conducted through its Account and Authorized Users.
              </p>
            </div>
          </section>

          {/* Section 6 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">6. Data Protection &amp; Processing Roles</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
              <div className="p-4 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800">
                <p className="font-medium text-gray-900 dark:text-white">Customer</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Acts as Data Controller</p>
              </div>
              <div className="p-4 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800">
                <p className="font-medium text-gray-900 dark:text-white">SuperSales</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">Acts as Data Processor</p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              SuperSales processes data solely on Customer instructions and only for the purpose of delivering the Services.
            </p>

            <h3 className="text-xl font-medium text-gray-900 dark:text-white mb-3 mt-6">Data Retention</h3>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>No audio files or call transcripts are stored by SuperSales.</li>
              <li>Transcripts are processed transiently and not retained after analysis.</li>
              <li>Only analytical results and session insights are retained, and only for the duration of the active Customer account.</li>
              <li>Upon account termination, all retained analytical data is deleted without delay.</li>
            </ul>
          </section>

          {/* Section 7 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">7. Data Subject Rights &amp; Requests</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              Customer may request:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2 mb-4">
              <li>Deletion of retained analytical data</li>
              <li>Export of available analytical outputs</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              Requests must be submitted via <strong>support@supersales.dev</strong>.
            </p>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              Response SLA: within 30 days, in accordance with applicable data protection laws.
            </p>
          </section>

          {/* Section 8 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">8. Acceptable Use</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              Customer shall not:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2 mb-4">
              <li>Use the Services unlawfully</li>
              <li>Upload Content without proper authorization</li>
              <li>Attempt to reverse engineer or exploit the platform</li>
              <li>Use the Services to develop or train competing products</li>
              <li>Interfere with security or availability of the Services</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              Third-Party Services are governed by their own terms and remain the Customer&apos;s responsibility.
            </p>
          </section>

          {/* Section 9 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">9. Artificial Intelligence Disclaimer</h2>
            <div className="p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg border border-purple-200 dark:border-purple-800 mb-4">
              <p className="text-purple-800 dark:text-purple-300 text-sm font-medium mb-2">Customer acknowledges that:</p>
              <ul className="list-disc pl-6 text-purple-700 dark:text-purple-300 text-sm space-y-1">
                <li>AI systems are probabilistic and may generate inaccurate or biased outputs</li>
                <li>AI Outputs must never be relied upon without human validation</li>
                <li>SuperSales disclaims liability for decisions, actions, or omissions taken based on AI Outputs</li>
                <li>AI Outputs do not constitute legal, financial, or professional advice</li>
              </ul>
            </div>
          </section>

          {/* Section 10 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">10. Intellectual Property</h2>

            <h3 className="text-xl font-medium text-gray-900 dark:text-white mb-3 mt-6">Customer Content</h3>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              Customer retains ownership of its Content and grants SuperSales a limited license to process it solely to provide the Services.
            </p>

            <h3 className="text-xl font-medium text-gray-900 dark:text-white mb-3 mt-6">SuperSales IP</h3>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              SuperSales retains exclusive ownership of:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2 mb-4">
              <li>Platform software and infrastructure</li>
              <li>Algorithms, models, methodologies, scoring logic</li>
              <li>Interfaces, workflows, and improvements</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              No rights are transferred except as expressly stated. Aggregated or anonymized insights may be used to improve the Services, without identifying Customer or individuals.
            </p>
          </section>

          {/* Section 11 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">11. Subscription, Billing &amp; Payment</h2>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-4">
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <p className="text-xs text-gray-500 dark:text-gray-500">Model</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">Subscription-based</p>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <p className="text-xs text-gray-500 dark:text-gray-500">Billing</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">Per seat</p>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <p className="text-xs text-gray-500 dark:text-gray-500">Processor</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">Stripe</p>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <p className="text-xs text-gray-500 dark:text-gray-500">Currency</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">EUR (&#8364;)</p>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <p className="text-xs text-gray-500 dark:text-gray-500">Free Trial</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">No</p>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <p className="text-xs text-gray-500 dark:text-gray-500">Commitment</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">No long-term</p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              Fees are payable in advance and non-refundable, except where required by law. Non-payment may result in suspension or termination of access.
            </p>
          </section>

          {/* Section 12 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">12. Suspension &amp; Termination</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              SuperSales may suspend or terminate access immediately if:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2 mb-4">
              <li>These Terms are breached</li>
              <li>Use poses legal, security, or reputational risk</li>
              <li>Fees remain unpaid</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              Customer may cancel its subscription in accordance with billing settings. Termination does not release Customer from outstanding payment obligations.
            </p>
          </section>

          {/* Section 13 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">13. Confidentiality</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              Each party shall protect the other&apos;s confidential information and use it solely to perform under these Terms.
            </p>
          </section>

          {/* Section 14 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">14. Warranties &amp; Disclaimers</h2>
            <div className="p-4 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800">
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Services are provided <strong>&quot;as is&quot;</strong> and <strong>&quot;as available&quot;</strong>. SuperSales disclaims all implied warranties, including fitness for a particular purpose and accuracy of AI Outputs.
              </p>
            </div>
          </section>

          {/* Section 15 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">15. Limitation of Liability</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              To the maximum extent permitted by law:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>SuperSales is not liable for indirect, incidental, or consequential damages, including loss of revenue, profit, or business opportunity.</li>
              <li>Total liability is capped at the Fees paid by Customer during the three (3) months preceding the claim.</li>
              <li>SuperSales is not liable for decisions made by Customer based on AI Outputs.</li>
            </ul>
          </section>

          {/* Section 16 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">16. Indemnification</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              Customer shall indemnify and hold harmless SuperSales from claims arising from:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>Unlawful recording or data processing</li>
              <li>Failure to obtain consent</li>
              <li>Violation of applicable laws</li>
              <li>Misuse of AI Outputs</li>
            </ul>
          </section>

          {/* Section 17 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">17. Governing Law &amp; Jurisdiction</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              These Terms are governed by the laws of the United Arab Emirates.
            </p>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              Any dispute falls under the exclusive jurisdiction of UAE courts.
            </p>
          </section>

          {/* Section 18 */}
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">18. Miscellaneous</h2>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li><strong className="text-gray-900 dark:text-white">Severability:</strong> invalid provisions do not affect the remainder</li>
              <li><strong className="text-gray-900 dark:text-white">Assignment:</strong> Customer may not assign without consent</li>
              <li><strong className="text-gray-900 dark:text-white">Entire Agreement:</strong> these Terms and referenced policies constitute the entire agreement</li>
              <li><strong className="text-gray-900 dark:text-white">Amendments:</strong> SuperSales may update these Terms with reasonable notice</li>
            </ul>
          </section>

        </div>
      </div>
    </div>
  )
}
