import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AI Usage & Disclaimer Policy | SuperSales',
  description: 'AI Usage & Disclaimer Policy for SuperSales - How we use AI and limitations of AI-generated outputs',
}

export default function AIUsagePolicyPage() {
  return (
    <div className="min-h-screen py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-12">
          <div className="inline-flex items-center px-3 py-1 rounded-full bg-purple-50 dark:bg-purple-950 text-purple-600 dark:text-purple-400 text-sm font-medium mb-4">
            AI Transparency
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-4">
            AI Usage &amp; Disclaimer Policy
          </h1>
          <div className="flex flex-col sm:flex-row sm:gap-6 text-gray-600 dark:text-gray-400">
            <p>Effective date: December 12, 2025</p>
            <p>Last updated: January 7, 2026</p>
          </div>
          <p className="text-sm text-gray-500 dark:text-gray-500 mt-2">Authoritative language: English</p>
        </div>

        {/* Introduction */}
        <div className="mb-10 p-6 bg-purple-50 dark:bg-purple-950/30 rounded-xl border border-purple-100 dark:border-purple-900">
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            This AI Usage &amp; Disclaimer Policy (&quot;AI Policy&quot;) describes how artificial intelligence (&quot;AI&quot;) is used within the SuperSales platform and defines the limitations, responsibilities, and risk allocation applicable to AI-generated outputs.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
            This AI Policy forms an integral part of the Terms of Service and must be read together with the Privacy Policy.
          </p>
        </div>

        {/* Content */}
        <div className="prose prose-gray dark:prose-invert max-w-none">
          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">1. Purpose of This Policy</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              The purpose of this AI Policy is to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>Ensure transparency regarding the use of AI within SuperSales</li>
              <li>Clearly define the non-decision-making nature of AI Outputs</li>
              <li>Allocate responsibilities between SuperSales and Customers</li>
              <li>Mitigate legal, regulatory, and operational risks related to AI use</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">2. Nature of AI Within SuperSales</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              SuperSales uses AI technologies to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>Analyze sales call transcriptions provided by Customers</li>
              <li>Generate scores, insights, coaching feedback, and recommendations</li>
              <li>Identify patterns and performance indicators within sales conversations</li>
            </ul>
            <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-950/30 rounded-lg border border-blue-100 dark:border-blue-900">
              <p className="text-blue-800 dark:text-blue-300 font-medium">
                AI is used exclusively as a decision-support tool.
              </p>
              <p className="text-blue-700 dark:text-blue-400 text-sm mt-2">
                SuperSales does not deploy AI to make automated decisions or decisions producing legal or similarly significant effects.
              </p>
            </div>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">3. Informational and Advisory Outputs Only</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              All AI Outputs generated by SuperSales are:
            </p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <span className="text-gray-900 dark:text-white font-medium">Informational</span>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <span className="text-gray-900 dark:text-white font-medium">Advisory</span>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <span className="text-gray-900 dark:text-white font-medium">Non-binding</span>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800 text-center">
                <span className="text-gray-900 dark:text-white font-medium">Non-deterministic</span>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              AI Outputs do not:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>Replace human judgment</li>
              <li>Constitute instructions or mandates</li>
              <li>Guarantee accuracy, completeness, or suitability</li>
            </ul>
            <div className="mt-6 p-4 bg-amber-50 dark:bg-amber-950/30 rounded-lg border border-amber-100 dark:border-amber-900">
              <p className="text-amber-800 dark:text-amber-300 font-semibold">
                Final decisions remain entirely and exclusively human.
              </p>
            </div>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">4. Human Validation Requirement</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              Customers acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>AI Outputs must always be reviewed, interpreted, and validated by qualified humans</li>
              <li>AI Outputs should never be acted upon automatically or without contextual analysis</li>
              <li>SuperSales is not responsible for actions taken without appropriate human oversight</li>
            </ul>
            <div className="mt-6 p-4 bg-red-50 dark:bg-red-950/30 rounded-lg border border-red-100 dark:border-red-900">
              <p className="text-red-800 dark:text-red-300 font-medium">
                Failure to implement human validation constitutes misuse of the Services.
              </p>
            </div>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">5. Limitations and Risks of AI</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              Customers expressly acknowledge that AI systems:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>Are probabilistic and may generate inaccurate or biased outputs</li>
              <li>Depend heavily on the quality, context, and completeness of input data</li>
              <li>May reflect limitations inherent to machine learning models</li>
              <li>Cannot account for all real-world variables, business contexts, or human factors</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mt-4 font-medium">
              SuperSales does not warrant that AI Outputs are error-free or fit for any specific purpose.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">6. No Professional or Commercial Advice</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              AI Outputs do not constitute:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2 mb-4">
              <li>Legal advice</li>
              <li>Financial advice</li>
              <li>Employment or HR advice</li>
              <li>Compliance advice</li>
              <li>Sales guarantees or performance commitments</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              SuperSales makes no representation regarding commercial success, revenue impact, or sales outcomes.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">7. Customer Responsibility and Risk Allocation</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              The Customer is solely responsible for:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>How AI Outputs are interpreted and used</li>
              <li>Any decisions, actions, or omissions based on AI Outputs</li>
              <li>Training and supervising personnel using the Services</li>
              <li>Ensuring AI Outputs are used in compliance with applicable laws and internal policies</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mt-4 font-medium">
              SuperSales shall not be liable for consequences arising from Customer reliance on AI Outputs.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">8. Data Quality and Bias Considerations</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              AI Outputs are influenced by:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>The accuracy and completeness of Customer-provided data</li>
              <li>Recording conditions and transcription quality</li>
              <li>Contextual nuances not detectable by AI</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mt-4">
              Customers are responsible for ensuring data quality and for identifying potential bias or misinterpretation.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">9. Regulatory Positioning</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              SuperSales is designed to operate as:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>A decision-support system</li>
              <li><strong>Not</strong> a high-risk or autonomous AI system</li>
              <li><strong>Not</strong> a system subject to automated decision-making restrictions under GDPR Article 22</li>
            </ul>
            <div className="mt-6 p-4 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800">
              <p className="text-gray-700 dark:text-gray-300 font-medium">
                This positioning is fundamental to the Services and must not be circumvented.
              </p>
            </div>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">10. Prohibited Uses of AI Outputs</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              Customers must not:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>Use AI Outputs as the sole basis for employment decisions</li>
              <li>Represent AI Outputs as authoritative or guaranteed</li>
              <li>Use AI Outputs in any context requiring certified professional judgment</li>
              <li>Remove or obscure AI disclaimers or limitations</li>
            </ul>
            <div className="mt-6 p-4 bg-red-50 dark:bg-red-950/30 rounded-lg border border-red-100 dark:border-red-900">
              <p className="text-red-800 dark:text-red-300 font-medium">
                Any such use constitutes a breach of the Terms of Service.
              </p>
            </div>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">11. Intellectual Property and AI</h2>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>AI models, methodologies, scoring logic, and analytical frameworks remain the exclusive intellectual property of SuperSales</li>
              <li>Customers acquire no rights to underlying AI technologies beyond the limited right to use AI Outputs within the Services</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">12. Updates to This AI Policy</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
              This AI Policy may be updated to reflect:
            </p>
            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
              <li>Legal or regulatory developments</li>
              <li>Advances in AI technologies</li>
              <li>Risk management considerations</li>
            </ul>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed mt-4">
              Material changes will be communicated through the Services or via email.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">13. Contact</h2>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
              For questions regarding AI usage or this policy:
            </p>
            <div className="mt-4 p-4 bg-gray-50 dark:bg-zinc-900 rounded-lg border border-gray-200 dark:border-zinc-800">
              <p className="text-gray-900 dark:text-white font-medium">SuperSales Support</p>
              <p className="text-gray-600 dark:text-gray-400">Email: support@supersales.dev</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}
